import type { CharacterId, CharacterProfile, FocusAction, StoryArc } from "../types";

export const CHARACTERS: Record<CharacterId, CharacterProfile> = {
  rina: {
    id: "rina",
    name: "璃奈",
    role: "温柔前辈",
    tag: "基本面主线",
    color: "pink",
    intro: "会把研报贴上粉色便签，也会认真盯着你的小金库。",
  },
  misaki: {
    id: "misaki",
    name: "美咲",
    role: "元气量化",
    tag: "短线波动线",
    color: "blue",
    intro: "拿着平板冲进会议室，最喜欢把概率说成心跳。",
  },
  mei: {
    id: "mei",
    name: "芽衣",
    role: "冷静宏观",
    tag: "周期策略线",
    color: "lavender",
    intro: "看起来很安静，但总能在大家慌乱前标出拐点。",
  },
};

export const STORY_ARCS: StoryArc[] = [
  {
    characterId: "rina",
    title: "序章：粉色便利贴",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "元气",
    line: "你在年初的投研部工位醒来，屏幕旁贴着一张粉色便利贴：这次的小金库，由我来监督你哦。",
    mission: "璃奈把四张心动情报卡排在桌上。选一张，再安排本话日程，开始重生路线。",
  },
  {
    characterId: "rina",
    title: "第一话：房租与奶茶预算",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "认真",
    line: "房租、通勤卡和奶茶预算同时报警。璃奈敲了敲你的桌面：先让账户活下来，再谈帅气登场吧。",
    mission: "本话选择会影响你的闪耀度，也会影响今天还能不能准时下班。",
  },
  {
    characterId: "misaki",
    title: "第二话：午休研报会",
    speaker: "美咲",
    role: "买方研究员",
    mood: "俏皮",
    line: "午休的咖啡还没凉，美咲就把一叠研报推过来：猜对本月主线的话，我请你吃甜点。",
    mission: "四张卡都很可爱，但真正的闪光路线藏在成交额和涨幅排名后面。",
  },
  {
    characterId: "rina",
    title: "第三话：雨夜加班CG",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "温柔",
    line: "雨点敲着玻璃，璃奈把外套搭在椅背上：今晚就当是我们的秘密作战会议吧。",
    mission: "选择本月赛道，决定你是继续补表格，还是进入璃奈的核心讨论。",
  },
  {
    characterId: "mei",
    title: "第四话：路演作战",
    speaker: "芽衣",
    role: "宏观策略师",
    mood: "沉着",
    line: "部门路演就要开始了。芽衣推了推眼镜：能把市场讲清楚的人，才配站在聚光灯下。",
    mission: "收益不是唯一指标，但收益会决定大家愿不愿意听完你的台词。",
  },
  {
    characterId: "rina",
    title: "第五话：末班车约定",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "害羞",
    line: "末班车里很安静。璃奈望着窗外，小声问：如果这次真的能改变未来，你会记得今天的约定吗？",
    mission: "本话情报会拉开分歧：追热点、看基本面，还是相信那条心跳加速的线索。",
  },
  {
    characterId: "misaki",
    title: "第六话：夏日中场复盘",
    speaker: "美咲",
    role: "买方研究员",
    mood: "兴奋",
    line: "半年过去，市场把很多人的自信晒化了。美咲托着下巴：所以，你靠的是重生记忆，还是喜欢她的直觉？",
    mission: "用一笔选择回答她：这条路线到底是奇迹，还是可以复盘的判断。",
  },
  {
    characterId: "mei",
    title: "第七话：闪耀发表会",
    speaker: "芽衣",
    role: "宏观策略师",
    mood: "观察",
    line: "发表会的灯亮起来。芽衣把你的账户曲线标上记号：这条线，开始有主角感了。",
    mission: "选对了，你从边缘座位进入主线；选错了，明天继续改 PPT。",
  },
  {
    characterId: "rina",
    title: "第八话：璃奈的深夜电话",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "在意",
    line: "电话那头停顿很久。璃奈说：这次我不替你选，但我会看着你的答案。",
    mission: "四个标的背后是四种分支，收益只是最直白的好感反馈。",
  },
  {
    characterId: "misaki",
    title: "第九话：风口心跳战",
    speaker: "美咲",
    role: "买方研究员",
    mood: "高涨",
    line: "所有群都在刷同一个方向，所有人都觉得自己是主角。美咲眨了眨眼：你也要冲进这段剧情吗？",
    mission: "在喧嚣里选择：跟随市场、逆向下注，还是相信成交额暴露出的真相。",
  },
  {
    characterId: "mei",
    title: "第十话：年末排名战",
    speaker: "芽衣",
    role: "宏观策略师",
    mood: "紧张",
    line: "年末排名开始倒计时。芽衣难得露出笑意：有人求稳，有人梭哈，而你还没有解锁最终 CG。",
    mission: "这次选择会决定结局基调：闪耀研究员、可靠打工人，还是疲劳值爆表。",
  },
  {
    characterId: "rina",
    title: "终章：收盘后的约定",
    speaker: "璃奈",
    role: "投研部前辈",
    mood: "心动",
    line: "最后一个月，城市灯光像一张温柔的 K 线图。璃奈看着你：不要只告诉我赚了多少，也告诉我你想进入哪条结局线。",
    mission: "完成最后一次选择，结算小金库、闪耀度、疲劳值和三位女主好感。",
  },
];

export const FOCUS_ACTIONS: FocusAction[] = [
  {
    id: "research",
    label: "熬夜研报",
    icon: "✦",
    short: "收益修正 +1.5%",
    detail: "把所有线索重新建模。更容易打出高收益，但疲劳值会上升。",
    returnBonus: 0.015,
    reputationDelta: 4,
    fatigueDelta: 8,
    affectionDelta: 1,
  },
  {
    id: "date",
    label: "角色约会",
    icon: "♡",
    short: "好感 +7",
    detail: "把晚上的复盘变成甜点作战会。收益不加成，但当前角色会更在意你。",
    returnBonus: 0,
    reputationDelta: 1,
    fatigueDelta: -3,
    affectionDelta: 7,
  },
  {
    id: "risk",
    label: "仓位纪律",
    icon: "◇",
    short: "疲劳 -9",
    detail: "少做一页 PPT，多睡一小时。执行更稳，但放弃一部分激进收益。",
    returnBonus: -0.005,
    reputationDelta: 2,
    fatigueDelta: -9,
    affectionDelta: 2,
  },
];

export const SIGNAL_TYPES = ["事件驱动", "业绩反转", "资金抱团", "政策风口", "产业链暗线", "高波动赌局"];
