import type {
  InvestigationChapterDefinition,
  InvestigationClueDefinition,
} from "./rebirth";

export const CLUES: Record<string, InvestigationClueDefinition> = {
  cost_drop: {
    label: "调用成本骤降",
    description: "发布材料证明单位调用价格快速下降，但没有说明利润如何分配。",
    reliability: "lead",
  },
  margin_gap: {
    label: "收入与利润断层",
    description: "调用增长可能被单价下滑和竞争投入抵消，收入增长不自动等于利润增长。",
    reliability: "verified",
  },
  payment_split: {
    label: "付费意愿分化",
    description: "大型企业愿意试点，中小客户仍在观望，部署能力决定付费转化。",
    reliability: "verified",
  },
  crowding_signal: {
    label: "动量拥挤",
    description: "短期收益主要由动量因子解释，成交结构仍强，但拥挤正在积累。",
    reliability: "lead",
  },
  competition_risk: {
    label: "赢家诅咒",
    description: "成本下降也降低进入壁垒，最热门的应用可能承受最激烈的竞争。",
    reliability: "counterexample",
  },
  clear_head: {
    label: "清醒输入",
    description: "停止继续摄入噪声后，你能更准确地区分自己知道什么、只是记得什么。",
    reliability: "state",
  },
  unit_economics: {
    label: "单位经济性",
    description: "把调用量、单价、毛利和获客投入放进同一张敏感性表，商业化节奏终于可检验。",
    reliability: "verified",
  },
  raw_factor_sample: {
    label: "原始失败区间",
    description: "完整样本显示热门因子在拥挤后的回撤远高于精选回测。",
    reliability: "counterexample",
  },
  staged_entry: {
    label: "观察仓方案",
    description: "先保留小仓位验证，再根据订单与利润数据增加暴露，降低等待的机会成本。",
    reliability: "verified",
  },

  apr_income_claim: {
    label: "一季报收入增长",
    description: "部分 AI 应用确实交出收入增长，但公告口径暂时无法说明增长质量。",
    reliability: "lead",
  },
  apr_quality_verified: {
    label: "收入质量交叉验证",
    description: "收入、毛利和客户留存同时改善的公司很少，纯概念与真实兑现开始分流。",
    reliability: "verified",
  },
  apr_tariff_exposure: {
    label: "关税暴露地图",
    description: "出口依赖、供应链替代能力和订单转移速度决定冲击方向，国产替代并非整条链同时受益。",
    reliability: "verified",
  },
  apr_price_reaction: {
    label: "公告后的资金确认",
    description: "业绩公告后的持续买入只集中在少数兑现标的，一次高开不能证明研究逻辑成立。",
    reliability: "lead",
  },
  apr_hindsight_gap: {
    label: "事后正确偏差",
    description: "你记得哪些公司后来上涨，却无法证明当时已经拥有足够证据区分兑现与概念。",
    reliability: "counterexample",
  },

  jul_upstream_profit: {
    label: "上游利润兑现",
    description: "算力租赁与基础设施毛利改善，应用端销售费用率却继续上升。",
    reliability: "verified",
  },
  jul_fund_flow_divergence: {
    label: "基本面与资金分歧",
    description: "收入改善的应用公司并未普遍获得持续资金，市场开始选择盈利质量而非故事完整度。",
    reliability: "lead",
  },
  jul_chain_heatmap: {
    label: "产业链景气热力图",
    description: "把收入、利润、订单和资金放在同一张图后，上游赚钱与下游烧钱的断层清晰可见。",
    reliability: "verified",
  },
  jul_failed_app_sample: {
    label: "被删掉的应用样本",
    description: "恢复失败样本后，应用端盈利拐点明显晚于精选公司给出的乐观印象。",
    reliability: "counterexample",
  },
  jul_rebalance_plan: {
    label: "分层再平衡",
    description: "将算力、平台和应用拆成不同验证周期，避免用一个仓位表达三种兑现速度。",
    reliability: "verified",
  },

  sep_rule_change: {
    label: "交易规则变化",
    description: "程序化交易报告制度改变了高频策略的可用空间，但影响需要通过真实成交数据确认。",
    reliability: "lead",
  },
  sep_factor_decay: {
    label: "因子衰减重测",
    description: "日内动量收益显著衰减，反转与低波因子的交易成本后收益开始改善。",
    reliability: "verified",
  },
  sep_access_channel: {
    label: "闭门数据权限",
    description: "赵承宇留下的合作信用让你看到公开报表之外的口径变更与失败回测。",
    reliability: "verified",
  },
  sep_recalibration_protocol: {
    label: "共同校准协议",
    description: "研究、量化和风控约定先统一样本与交易成本，再讨论因子是否失效。",
    reliability: "verified",
  },
  sep_microstructure_risk: {
    label: "微观结构生存边界",
    description: "规则变化先影响成交方式与回撤，再传导到组合收益，旧止损线已经失真。",
    reliability: "counterexample",
  },

  dec_full_year_errors: {
    label: "全年错误清单",
    description: "十二个月的档案显示，最有价值的记录来自假设被推翻的位置，而非结论命中的次数。",
    reliability: "verified",
  },
  dec_memory_provenance: {
    label: "记忆来源比对",
    description: "未来记忆与后来财经标题高度重合，部分所谓亲历记忆可能来自事后叙事覆盖。",
    reliability: "counterexample",
  },
  dec_counterfactual: {
    label: "失败月份反事实",
    description: "重新放回被忽略的失败样本后，未来并没有单一正确路线，只有不同代价的研究框架。",
    reliability: "counterexample",
  },
  dec_sustainable_framework: {
    label: "可持续研究边界",
    description: "把身体状态、机会成本和退出条件写进框架，研究能力才不会依赖一次透支。",
    reliability: "verified",
  },
  dec_truth_hypothesis: {
    label: "被污染的未来假设",
    description: "你确实经历过未来，但记住的是后来被市场反复讲述的版本。未来记忆需要和任何二手材料一样被审计。",
    reliability: "verified",
  },
};

export const INVESTIGATION_CHAPTERS: Record<string, InvestigationChapterDefinition> = {
  "2025-01": {
    monthKey: "2025-01",
    title: "未来记忆审计",
    thesis: "先确认技术突破，再追问成本下降如何传导到收入、利润和竞争格局。",
    timeBudget: 6,
    keyMonth: true,
    nodes: [
      {
        id: "public_materials",
        label: "阅读发布材料和公开报道",
        summary: "确认技术突破与调用价格变化，避免拿二手情绪当原始事实。",
        cost: 1,
        clueId: "cost_drop",
      },
      {
        id: "financial_model",
        label: "拆应用公司的收入与成本模型",
        summary: "把调用量、单价、毛利率和获客投入拆开，寻找商业化传导缺口。",
        cost: 2,
        clueId: "margin_gap",
        requiresCompleted: ["public_materials"],
        effects: { researchCredibility: 2, fatigue: 2 },
      },
      {
        id: "cio_calls",
        label: "联系企业 CIO 做电话调研",
        summary: "绕过概念宣传，询问预算、部署难度和真实续费意愿。",
        cost: 2,
        clueId: "payment_split",
        shortcut: "lin_contact_book",
        effects: { teamTrust: 1, fatigue: 1, relations: { lin_ruoning: 1 } },
      },
      {
        id: "factor_crowding",
        label: "在量化终端检查因子拥挤",
        summary: "拆解收益来源、盘口厚度和 Alpha 衰减，判断短期强势有多少来自情绪。",
        cost: 2,
        clueId: "crowding_signal",
        shortcut: "zhao_factor_pipeline",
        effects: {
          researchCredibility: 1,
          fatigue: 2,
          relations: { chen_xinghe: 1, zhao_chengyu: 1 },
        },
      },
      {
        id: "risk_review",
        label: "和周明昭做竞争与下行情景",
        summary: "讨论成本下降如何改变进入壁垒，并提前写清错误边界。",
        cost: 1,
        clueId: "competition_risk",
        shortcut: "zhou_risk_template",
        effects: { relations: { zhou_mingzhao: 1 } },
      },
      {
        id: "rest",
        label: "停止刷屏，准时休息",
        summary: "把一个时间块留给睡眠，让明天的判断不再接收被疲劳污染的输入。",
        cost: 1,
        clueId: "clear_head",
        effects: { fatigue: -8, lifeBalance: 8 },
      },
      {
        id: "unit_economics",
        label: "建立单位经济性敏感性表",
        summary: "利用上一周目的因果缺口，把调用量增长和利润增长放进同一套可证伪模型。",
        cost: 1,
        clueId: "unit_economics",
        requiresKey: "causal_gap",
        requiresCompleted: ["financial_model"],
        effects: { researchCredibility: 2, fatigue: 1 },
      },
      {
        id: "raw_factor_check",
        label: "恢复回测中的失败区间",
        summary: "利用样本污染记忆，检查被筛掉的月份、异常值和拥挤后的回撤。",
        cost: 1,
        clueId: "raw_factor_sample",
        requiresKey: "sample_pollution",
        requiresCompleted: ["factor_crowding"],
        effects: { researchCredibility: 1, fatigue: 1 },
      },
      {
        id: "staged_entry",
        label: "设计观察仓与分阶段验证",
        summary: "利用机会成本记忆，把等待和追涨之间的二选一改成可调整路径。",
        cost: 1,
        clueId: "staged_entry",
        requiresKey: "opportunity_cost",
        requiresCompleted: ["risk_review"],
        effects: { researchCredibility: 1 },
      },
    ],
  },

  "2025-04": {
    monthKey: "2025-04",
    title: "结果正确与证据完整",
    thesis: "一季报让结论接受现实检验。真正的问题是，当时的证据是否足以得到今天的答案。",
    timeBudget: 5,
    keyMonth: true,
    nodes: [
      {
        id: "apr_earnings_scan",
        label: "扫描一季报收入兑现",
        summary: "先标出收入增长与纯概念分流，再决定哪些公司值得继续验证。",
        cost: 1,
        clueId: "apr_income_claim",
      },
      {
        id: "apr_margin_retention",
        label: "交叉验证毛利与客户留存",
        summary: "把收入增速、毛利变化和留存放在一起，检查增长质量。",
        cost: 2,
        clueId: "apr_quality_verified",
        requiresCompleted: ["apr_earnings_scan"],
        effects: { researchCredibility: 2, fatigue: 2, relations: { lin_ruoning: 1 } },
      },
      {
        id: "apr_tariff_map",
        label: "绘制关税暴露与替代地图",
        summary: "拆出口依赖、供应链替代和订单迁移，避免把国产替代当成统一利好。",
        cost: 1,
        clueId: "apr_tariff_exposure",
        shortcut: "zhou_risk_template",
        effects: { relations: { zhou_mingzhao: 1 } },
      },
      {
        id: "apr_price_confirmation",
        label: "检查公告后的资金确认",
        summary: "观察业绩公告后的成交持续性，区分一次高开和真实重定价。",
        cost: 1,
        clueId: "apr_price_reaction",
        shortcut: "zhao_factor_pipeline",
        effects: { relations: { chen_xinghe: 1 } },
      },
      {
        id: "apr_hindsight_audit",
        label: "把正确结论拆回事前证据",
        summary: "利用因果缺口钥匙，逐项标出当时已知、后来补充和纯粹记住的内容。",
        cost: 1,
        clueId: "apr_hindsight_gap",
        requiresCycle: 2,
        requiresKey: "causal_gap",
        requiresCompleted: ["apr_margin_retention"],
        effects: { researchCredibility: 2, lifeBalance: 1 },
      },
    ],
  },

  "2025-07": {
    monthKey: "2025-07",
    title: "产业链与资金分化",
    thesis: "中报同时暴露业务兑现和市场选择。基本面正确，并不保证资金在同一时点认可。",
    timeBudget: 5,
    keyMonth: true,
    nodes: [
      {
        id: "jul_segment_margins",
        label: "拆分产业链分部利润",
        summary: "比较算力、平台和应用端的收入质量与费用投入。",
        cost: 1,
        clueId: "jul_upstream_profit",
        effects: { researchCredibility: 1, relations: { lin_ruoning: 1 } },
      },
      {
        id: "jul_flow_split",
        label: "检查中报后的资金留存",
        summary: "观察哪些兑现方向获得持续买入，哪些只得到一次公告脉冲。",
        cost: 1,
        clueId: "jul_fund_flow_divergence",
        shortcut: "zhao_factor_pipeline",
        effects: { relations: { chen_xinghe: 1 } },
      },
      {
        id: "jul_chain_heatmap",
        label: "合成产业链景气热力图",
        summary: "把业务利润和资金选择叠在同一张图上，定位兑现节奏的断层。",
        cost: 2,
        clueId: "jul_chain_heatmap",
        requiresCompleted: ["jul_segment_margins", "jul_flow_split"],
        effects: { researchCredibility: 2, fatigue: 2 },
      },
      {
        id: "jul_failure_sample",
        label: "恢复盈利拐点失败样本",
        summary: "利用样本污染钥匙，把被精选案例遮住的失败应用重新放回样本。",
        cost: 1,
        clueId: "jul_failed_app_sample",
        requiresCycle: 2,
        requiresKey: "sample_pollution",
        requiresCompleted: ["jul_flow_split"],
        effects: { researchCredibility: 1 },
      },
      {
        id: "jul_rebalance",
        label: "设计产业链分层再平衡",
        summary: "利用机会成本钥匙，为三种兑现周期分别设置验证和调整条件。",
        cost: 1,
        clueId: "jul_rebalance_plan",
        requiresKey: "opportunity_cost",
        requiresCompleted: ["jul_chain_heatmap"],
        effects: { relations: { zhou_mingzhao: 1 } },
      },
    ],
  },

  "2025-09": {
    monthKey: "2025-09",
    title: "规则变化与组织权限",
    thesis: "微观结构变化需要重新校准样本、成本和风控。谁愿意把原始数据交给你，同样是研究能力的一部分。",
    timeBudget: 5,
    keyMonth: true,
    nodes: [
      {
        id: "sep_rule_text",
        label: "拆解程序化交易新规",
        summary: "先确认报告制度改变了哪些行为边界，再提出因子失效假设。",
        cost: 1,
        clueId: "sep_rule_change",
      },
      {
        id: "sep_factor_retest",
        label: "按新口径重跑因子收益",
        summary: "加入交易成本与报告约束，重新测试动量、反转和低波因子。",
        cost: 2,
        clueId: "sep_factor_decay",
        requiresCompleted: ["sep_rule_text"],
        shortcut: "zhao_factor_pipeline",
        effects: { researchCredibility: 2, fatigue: 2, relations: { chen_xinghe: 1 } },
      },
      {
        id: "sep_closed_door_access",
        label: "调用量化组闭门失败样本",
        summary: "使用过去合作积累的权限，查看公开报表中没有出现的失败回测。",
        cost: 0,
        clueId: "sep_access_channel",
        requiresShortcut: "zhao_factor_pipeline",
        effects: { teamTrust: 1, relations: { zhao_chengyu: 1 } },
      },
      {
        id: "sep_shared_protocol",
        label: "建立共同校准协议",
        summary: "统一样本、交易成本和失效定义，让研究与量化在同一张桌上复算。",
        cost: 1,
        clueId: "sep_recalibration_protocol",
        requiresCompleted: ["sep_factor_retest", "sep_closed_door_access"],
        effects: { teamTrust: 2, relations: { zhao_chengyu: 1, chen_xinghe: 1 } },
      },
      {
        id: "sep_microstructure_risk",
        label: "重画微观结构风险边界",
        summary: "检查旧止损和流动性假设是否仍然有效，先保护组合生存。",
        cost: 1,
        clueId: "sep_microstructure_risk",
        shortcut: "zhou_risk_template",
        effects: { relations: { zhou_mingzhao: 1 } },
      },
    ],
  },

  "2025-12": {
    monthKey: "2025-12",
    title: "年度档案与真相路线",
    thesis: "收官不是统计命中率。你需要审计全年证据、失败样本、身体代价和未来记忆的来源。",
    timeBudget: 6,
    keyMonth: true,
    nodes: [
      {
        id: "dec_archive_audit",
        label: "审计全年研究档案",
        summary: "按月份标出假设、证据、反例和业务结果，整理真正的错误清单。",
        cost: 1,
        clueId: "dec_full_year_errors",
        requiresFlag: "office_archive_reviewed",
        effects: { researchCredibility: 2 },
      },
      {
        id: "dec_compare_memory",
        label: "比对未来记忆与后来标题",
        summary: "利用因果缺口钥匙，检查哪些细节来自亲历，哪些更像后来形成的共识。",
        cost: 1,
        clueId: "dec_memory_provenance",
        requiresCycle: 2,
        requiresKey: "causal_gap",
        effects: { researchCredibility: 1 },
      },
      {
        id: "dec_replay_failures",
        label: "重放被删掉的失败月份",
        summary: "利用样本污染钥匙，把失败区间重新放回全年叙事，检查唯一正确路线是否存在。",
        cost: 1,
        clueId: "dec_counterfactual",
        requiresCycle: 2,
        requiresKey: "sample_pollution",
      },
      {
        id: "dec_boundary_review",
        label: "把身体与机会成本写进框架",
        summary: "检查这一年的研究能力是否依赖透支，以及谨慎错过了哪些可管理的机会。",
        cost: 1,
        clueId: "dec_sustainable_framework",
        requiresAnyKey: ["body_memory", "opportunity_cost"],
        effects: { fatigue: -2, lifeBalance: 2 },
      },
      {
        id: "dec_truth_synthesis",
        label: "提出被污染的未来假设",
        summary: "把档案、反事实和记忆来源合并，形成一套能解释所有异常的新假设。",
        cost: 2,
        clueId: "dec_truth_hypothesis",
        requiresCycle: 2,
        requiresCompleted: [
          "dec_archive_audit",
          "dec_compare_memory",
          "dec_replay_failures",
          "dec_boundary_review"
        ],
        effects: { researchCredibility: 3, teamTrust: 2 },
      },
    ],
  },
};

export const INVESTIGATION_NODES = Object.values(INVESTIGATION_CHAPTERS)
  .flatMap((chapter) => chapter.nodes);

export function chapterForMonth(monthKey: string): InvestigationChapterDefinition | null {
  return INVESTIGATION_CHAPTERS[monthKey] ?? null;
}
