name: Export source

on:
  pull_request:

permissions:
  contents: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: source-tree
          path: .
          include-hidden-files: true
          retention-days: 1
